const SPRoutes = {
    SPSignup: "/sp/signup",
    spOtpVerify: "/sp/otpVerify",
    OtpResend: "/sp/resendOtp",
    SPLogin: "/sp/login",
    getProfile: "/sp/getProfile",
    updateProfile: "/sp/editProfile",
    changePassword: "/sp/changePassword",
    changeProfileImage:"/sp/upload-profile-image",
    addDepartment: "/sp/addDepartment",
    updateDepartment:"/sp/editDepartment",
    changeFirstDocumentImage: "/sp/changeFirstDocumentImage",
    changeSecondDocumentImage: "/sp/changeSecondDocumentImage",
    getAllServiceDetails:"/sp/getAllServiceDetails",
    deleteDepartment:"/sp/deleteDepartment",
    getFullAppointmentList:"/sp/getFullAppointmentList",
    appointmentApprove:"/sp/appointmentApprove",
    appointmentCancel:"/sp/appointmentCancel",
    getRatingsAndReviews:"/sp/getRatingsAndReviews",
    completeAppointment:"/sp/completeAppointment",
    getEmergencyNumber:"/sp/getEmergencyNumber",
    updateEmergencyNumber:"/sp/updateEmergencyNumber",
    deleteEmergencyNumber:"/sp/deleteEmergencyNumber",
    changeDoctorProfileImage:"/sp/changeDoctorProfileImage",
    getDoctorDetails:"/sp/getDoctorDetails",
    getAppointmentDetails:"/sp/getAppointmentDetails",
    addPrescriptionToAppointment:"/sp/addPrescriptionToAppointment",
    getPrescription:"/sp/getPrescription",
    getRecentAppointments:"/sp/getRecentAppointments",
    addDoctorToDepartment:"/sp/addDoctorToDepartment",
    updateDoctorDetails:"/sp/updateDoctorDetails",
    getAllDoctorDetailsInsideADepartment:"/sp/getAllDoctorDetailsInsideADepartment",
    getDoctorSlotsDetails:"/sp/getDoctorSlotsDetails",
    isDoctorHaveSlots:"/sp/isDoctorHaveSlots",
    deleteDoctor:"/sp/deleteDoctor",
  };
  export default SPRoutes;
